DEFAULT_WORKING_EMAIL = "working_email1@email.com"
DEFAULT_WORKING_PASSWORD = "working_password"
DEFAULT_NAME = "user_first_name"

EXAMPLE_CUSTOM_FOOD_INPUT = {
    "name": "test_custom_food",
    "carbs": 0,
    "protein": 0,
    "fat": 0,
    "kcal": 0,
    "barcode": "12312123",
    "alcohol": 0,
    "caffeine": 0,
    "vitamins": {
        "vit_a": 0,
        "vit_b1": 0,
        "vit_b2": 0,
        "vit_b3": 0,
        "pantothenic_acid": 0,
        "vit_b6": 0,
        "vit_b7": 0,
        "biotin": 0,
        "vit_b9": 0,
        "vit_b12": 0,
        "vit_c": 0,
        "vit_d": 0,
        "vit_e": 0,
        "vit_k": 0,
    },
    "minerals": {
        "calcium": 0,
        "magnesium": 0,
        "phosphorus": 0,
        "sodium": 0,
        "sulfur": 0,
        "iron": 0,
        "zinc": 0,
        "copper": 0,
        "manganese": 0,
        "molybdenum": 0,
        "selenium": 0,
        "iodine": 0,
        "fluoride": 0,
        "chromium": 0,
        "potassium": 0,
        "taurine": 0,
    },
    "fats": {
        "saturated_fat": 0,
        "monounsaturated_fat": 0,
        "polyunsaturated_fat": 0,
        "omega_3_fat": 0,
        "omega_6_fat": 0,
        "omega_9_fat": 0,
        "trans_fat": 0,
    },
}
