"""Add user_id to food, foodEntry, foodEntryItem

Revision ID: 02a032d202f8
Revises: 15a560d31e5c
Create Date: 2026-06-01 10:47:32.214125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02a032d202f8'
down_revision: Union[str, Sequence[str], None] = '15a560d31e5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_food_user_id'), 'food', ['user_id'], unique=False)
    op.create_foreign_key(None, 'food', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('food_entry', sa.Column('user_id', sa.UUID(), nullable=False, as_uuid=True, server_default="7c77678c-1826-4d5a-8666-c02e94985003"))
    op.create_foreign_key(None, 'food_entry', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'food_entry', type_='foreignkey')
    op.drop_column('food_entry', 'user_id')
    op.drop_constraint(None, 'food', type_='foreignkey')
    op.drop_index(op.f('ix_food_user_id'), table_name='food')
    op.drop_column('food', 'user_id')
    # ### end Alembic commands ###
