"""initial schema

Revision ID: 573dd7ab1f54
Revises:
Create Date: 2026-07-10 15:19:50.431728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '573dd7ab1f54'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('food',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('carbs', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('protein', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fat', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('kcal', sa.Integer(), nullable=False),
    sa.Column('alcohol', sa.Integer(), nullable=True),
    sa.Column('caffeine', sa.Integer(), nullable=True),
    sa.Column('barcode', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_food_name_trgm', 'food', ['name'], unique=False, postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.create_index(op.f('ix_food_user_id'), 'food', ['user_id'], unique=False)
    op.create_table('food_entry',
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('user_id', 'name', name='uq_recipe_user_name')
    )
    op.create_table('fats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('saturated_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('monounstaurated_fat', sa.Float(), nullable=True),
    sa.Column('polyunsaturated_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('omega_3_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('omega_6_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('omega_9_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trans_fat', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_entry_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('food_grams', sa.Integer(), nullable=False),
    sa.Column('food_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['food_entry_id'], ['food_entry.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('minerals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('calcium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('magnesium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('phosphorus', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sodium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sulfur', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('iron', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('zinc', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('copper', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('manganese', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('molybdenum', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('selenium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('iodine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fluoride', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('chromium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('potassium', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taurine', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('food_id', sa.UUID(), nullable=False),
    sa.Column('food_grams', sa.Integer(), nullable=False),
    sa.Column('food_entry_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['food_entry_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vitamins',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vit_a', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b1', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b2', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b3', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pantothenic_acid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b6', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b7', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('biotin', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b9', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_b12', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_c', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_d', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_e', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('vit_k', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vitamins')
    op.drop_table('recipe_item')
    op.drop_table('minerals')
    op.drop_table('food_entry_item')
    op.drop_table('fats')
    op.drop_table('recipe')
    op.drop_table('food_entry')
    op.drop_index(op.f('ix_food_user_id'), table_name='food')
    op.drop_index('idx_food_name_trgm', table_name='food', postgresql_using='gin', postgresql_ops={'name': 'gin_trgm_ops'})
    op.drop_table('food')
    op.drop_table('user')
    # ### end Alembic commands ###
