"""add recipe and recipe_item table

Revision ID: 628fbebd9120
Revises: 02a032d202f8
Create Date: 2026-06-06 19:37:35.784302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '628fbebd9120'
down_revision: Union[str, Sequence[str], None] = '02a032d202f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('recipe_name', sa.String(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False, as_uuid=True),
    sa.Column('user_id', sa.UUID(), nullable=False, as_uuid=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recipe_item',
    sa.Column('id', sa.UUID(), nullable=False, as_uuid=True),
    sa.Column('food_id', sa.UUID(), nullable=False, as_uuid=True),
    sa.Column('food_grams', sa.Integer(), nullable=False),
    sa.Column('food_entry_id', sa.UUID(), nullable=True, as_uuid=True),
    sa.ForeignKeyConstraint(['food_entry_id'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['food.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('food_entry_item', 'food_entry_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('food_entry_item', 'food_entry_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_table('recipe_item')
    op.drop_table('recipe')
    # ### end Alembic commands ###
