"""add optional name column to FoodEntry

Revision ID: 7d81f901e458
Revises: 628fbebd9120
Create Date: 2026-06-15 22:28:08.366801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d81f901e458'
down_revision: Union[str, Sequence[str], None] = '628fbebd9120'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('food_entry', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('food_entry', 'name')
    # ### end Alembic commands ###
