"""recipe.recipe_name to recipe.name

Revision ID: ebcbbb8d83ac
Revises: 85f81f4470f6
Create Date: 2026-06-22 14:43:13.424584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebcbbb8d83ac'
down_revision: Union[str, Sequence[str], None] = '85f81f4470f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("recipe", "recipe_name", new_column_name="name")
    op.create_unique_constraint('uq_recipe_user_name', 'recipe', ['user_id', 'name'])
    op.create_unique_constraint(None, 'recipe', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='unique')
    op.drop_constraint('uq_recipe_user_name', 'recipe', type_='unique')
    op.alter_column("recipe", "name", new_column_name="recipe_name")    # ### end Alembic commands ###
