/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/search/name/{food_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food By Name */
        get: operations["search_food_by_name_api_search_name__food_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/specific/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food By Uuid */
        get: operations["search_food_by_uuid_api_search_specific__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/date/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food Entries By Date */
        get: operations["search_food_entries_by_date_api_search_date__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search/food_entries/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All Food Entries */
        get: operations["all_food_entries_api_search_food_entries_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/create_food_entry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Food Entry */
        post: operations["create_food_entry_api_create_food_entry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/create_custom_food": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Custom Food */
        post: operations["create_custom_food_api_create_custom_food_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Fats */
        Fats: {
            /**
             * Saturated Fat
             * @default 0
             */
            saturated_fat: number | null;
            /**
             * Monounstaurated Fat
             * @default 0
             */
            monounstaurated_fat: number | null;
            /**
             * Polyunsaturated Fat
             * @default 0
             */
            polyunsaturated_fat: number | null;
            /**
             * Omage 3 Fat
             * @default 0
             */
            omage_3_fat: number | null;
            /**
             * Omage 6 Fat
             * @default 0
             */
            omage_6_fat: number | null;
            /**
             * Omage 9 Fat
             * @default 0
             */
            omage_9_fat: number | null;
            /**
             * Trans Fat
             * @default 0
             */
            trans_fat: number | null;
        };
        /** FoodEntryItemOut */
        "FoodEntryItemOut-Input": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Food Id
             * Format: uuid
             */
            food_id: string;
            /** Food Grams */
            food_grams: number;
            food: components["schemas"]["FoodOut"];
        };
        /** FoodEntryItemOut */
        "FoodEntryItemOut-Output": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Food Id
             * Format: uuid
             */
            food_id: string;
            /** Food Grams */
            food_grams: number;
            food: components["schemas"]["FoodOut"];
        };
        /** FoodEntryOut */
        "FoodEntryOut-Input": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Food Items */
            food_items: components["schemas"]["FoodEntryItemOut-Input"][];
        };
        /** FoodEntryOut */
        "FoodEntryOut-Output": {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Food Items */
            food_items: components["schemas"]["FoodEntryItemOut-Output"][];
            /** Name */
            readonly name: string;
            /** Protein */
            readonly protein: number;
            /** Carbs */
            readonly carbs: number;
            /** Fat */
            readonly fat: number;
            /** Kcal */
            readonly kcal: number;
            /** Alcohol */
            readonly alcohol: number;
            /** Caffeine */
            readonly caffeine: number;
            /** Food Grams */
            readonly food_grams: number;
        };
        /** FoodOut */
        FoodOut: {
            /** Name */
            name: string;
            /** Carbs */
            carbs: number;
            /** Protein */
            protein: number;
            /** Fat */
            fat: number;
            /** Kcal */
            kcal: number;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Alcohol
             * @default 0
             */
            alcohol: number | null;
            /**
             * Caffeine
             * @default 0
             */
            caffeine: number | null;
            /** Barcode */
            barcode: string;
            vitamins: components["schemas"]["Vitamins"] | null;
            minerals: components["schemas"]["Minerals"] | null;
            fats: components["schemas"]["Fats"] | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Minerals */
        Minerals: {
            /**
             * Calcium
             * @default 0
             */
            calcium: number | null;
            /**
             * Magnesium
             * @default 0
             */
            magnesium: number | null;
            /**
             * Phosphorus
             * @default 0
             */
            phosphorus: number | null;
            /**
             * Sodium
             * @default 0
             */
            sodium: number | null;
            /**
             * Sulfur
             * @default 0
             */
            sulfur: number | null;
            /**
             * Iron
             * @default 0
             */
            iron: number | null;
            /**
             * Zinc
             * @default 0
             */
            zinc: number | null;
            /**
             * Copper
             * @default 0
             */
            copper: number | null;
            /**
             * Manganese
             * @default 0
             */
            manganese: number | null;
            /**
             * Molybdenum
             * @default 0
             */
            molybdenum: number | null;
            /**
             * Selenium
             * @default 0
             */
            selenium: number | null;
            /**
             * Iodine
             * @default 0
             */
            iodine: number | null;
            /**
             * Fluoride
             * @default 0
             */
            fluoride: number | null;
            /**
             * Chromium
             * @default 0
             */
            chromium: number | null;
            /**
             * Potassium
             * @default 0
             */
            potassium: number | null;
            /**
             * Taurine
             * @default 0
             */
            taurine: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vitamins */
        Vitamins: {
            /**
             * Vit A
             * @default 0
             */
            vit_a: number | null;
            /**
             * Vit B1
             * @default 0
             */
            vit_b1: number | null;
            /**
             * Vit B2
             * @default 0
             */
            vit_b2: number | null;
            /**
             * Vit B3
             * @default 0
             */
            vit_b3: number | null;
            /**
             * Pantothenic Acid
             * @default 0
             */
            pantothenic_acid: number | null;
            /**
             * Vit B6
             * @default 0
             */
            vit_b6: number | null;
            /**
             * Vit B7
             * @default 0
             */
            vit_b7: number | null;
            /**
             * Biotin
             * @default 0
             */
            biotin: number | null;
            /**
             * Vit B9
             * @default 0
             */
            vit_b9: number | null;
            /**
             * Vit B12
             * @default 0
             */
            vit_b12: number | null;
            /**
             * Vit C
             * @default 0
             */
            vit_c: number | null;
            /**
             * Vit D
             * @default 0
             */
            vit_d: number | null;
            /**
             * Vit E
             * @default 0
             */
            vit_e: number | null;
            /**
             * Vit K
             * @default 0
             */
            vit_k: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    search_food_by_name_api_search_name__food_name__get: {
        parameters: {
            query?: {
                iteration?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                food_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_food_by_uuid_api_search_specific__get: {
        parameters: {
            query?: {
                food_uuid?: string | null;
                barcode?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_food_entries_by_date_api_search_date__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOut-Output"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    all_food_entries_api_search_food_entries_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOut-Output"][];
                };
            };
        };
    };
    create_food_entry_api_create_food_entry_post: {
        parameters: {
            query: {
                food_uuid: string;
                grams: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_custom_food_api_create_custom_food_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
