/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/foods/custom-foods": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Custom Food */
        get: operations["get_user_custom_food_api_foods_custom_foods_get"];
        put?: never;
        /** Create Custom Food */
        post: operations["create_custom_food_api_foods_custom_foods_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/{food_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food By Name */
        get: operations["search_food_by_name_api_foods__food_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/foods/custom-foods/{food_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Custom Food */
        put: operations["edit_custom_food_api_foods_custom_foods__food_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User Recipes */
        get: operations["get_user_recipes_api_recipes_get"];
        put?: never;
        /** Create Recipe */
        post: operations["create_recipe_api_recipes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Recipe */
        put: operations["edit_recipe_api_recipes__recipe_id__put"];
        post?: never;
        /** Remove Recipe */
        delete: operations["remove_recipe_api_recipes__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recipes/{recipe_id}/food-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Entry From Recipe */
        post: operations["create_entry_from_recipe_api_recipes__recipe_id__food_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food-entries/{date}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search Food Entries By Date */
        get: operations["search_food_entries_by_date_api_food_entries__date__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food-entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Food Entry */
        post: operations["create_food_entry_api_food_entries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food-entries/{food_entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Edit Food Entry Food Items */
        put: operations["edit_food_entry_food_items_api_food_entries__food_entry_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/food-entries/{food_entry_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Food Entry */
        delete: operations["remove_food_entry_api_food_entries__food_entry_uuid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create User */
        post: operations["create_user_api_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_api_users_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get Current User */
        post: operations["get_current_user_api_users_me_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_users__user_id__patch"];
        trace?: never;
    };
    "/api/food-entry-items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Food Entry Item */
        patch: operations["edit_food_entry_item_api_food_entry_items__item_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_api_users_token_post */
        Body_login_for_access_token_api_users_token_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CreateUser */
        CreateUser: {
            /** Name */
            name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** CustomFoodInput */
        CustomFoodInput: {
            /** Name */
            name: string;
            /** Carbs */
            carbs: number;
            /** Protein */
            protein: number;
            /** Fat */
            fat: number;
            /** Kcal */
            kcal: number;
            /** Barcode */
            barcode: string | null;
            /**
             * Alcohol
             * @default 0
             */
            alcohol: number | null;
            /**
             * Caffeine
             * @default 0
             */
            caffeine: number | null;
            vitamins: components["schemas"]["Vitamins"] | null;
            minerals: components["schemas"]["Minerals"] | null;
            fats: components["schemas"]["Fats"] | null;
        };
        /** EntryItemInput */
        EntryItemInput: {
            /**
             * Food Uuid
             * Format: uuid
             */
            food_uuid: string;
            /** Grams */
            grams: number;
        };
        /** ExistingEntryItemInput */
        ExistingEntryItemInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Food Grams */
            food_grams: number;
        };
        /** ExistingRecipeItemInput */
        ExistingRecipeItemInput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Food Grams */
            food_grams: number;
        };
        /** Fats */
        Fats: {
            /**
             * Saturated Fat
             * @default 0
             */
            saturated_fat: number | null;
            /**
             * Monounsaturated Fat
             * @default 0
             */
            monounsaturated_fat: number | null;
            /**
             * Polyunsaturated Fat
             * @default 0
             */
            polyunsaturated_fat: number | null;
            /**
             * Omega 3 Fat
             * @default 0
             */
            omega_3_fat: number | null;
            /**
             * Omega 6 Fat
             * @default 0
             */
            omega_6_fat: number | null;
            /**
             * Omega 9 Fat
             * @default 0
             */
            omega_9_fat: number | null;
            /**
             * Trans Fat
             * @default 0
             */
            trans_fat: number | null;
        };
        /** FoodEntryItemEdit */
        FoodEntryItemEdit: {
            /** Grams */
            grams: number;
        };
        /** FoodEntryItemOutput */
        FoodEntryItemOutput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Food Id
             * Format: uuid
             */
            food_id: string;
            /** Food Grams */
            food_grams: number;
            food: components["schemas"]["FoodOutput"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Food Entry Id
             * Format: uuid
             */
            food_entry_id: string;
        };
        /** FoodEntryOutput */
        FoodEntryOutput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Name */
            name?: string | null;
            /** Food Items */
            food_items: components["schemas"]["FoodEntryItemOutput"][];
            /**
             * Kcal
             * @default 0
             */
            kcal: number;
            /**
             * Protein
             * @default 0
             */
            protein: number;
            /**
             * Fat
             * @default 0
             */
            fat: number;
            /**
             * Carbs
             * @default 0
             */
            carbs: number;
            /**
             * Alcohol
             * @default 0
             */
            alcohol: number;
            /**
             * Caffeine
             * @default 0
             */
            caffeine: number;
            /**
             * Food Grams
             * @default 0
             */
            food_grams: number;
        };
        /** FoodOutput */
        FoodOutput: {
            /** Name */
            name: string;
            /** Carbs */
            carbs: number;
            /** Protein */
            protein: number;
            /** Fat */
            fat: number;
            /** Kcal */
            kcal: number;
            /** Barcode */
            barcode: string | null;
            /**
             * Alcohol
             * @default 0
             */
            alcohol: number | null;
            /**
             * Caffeine
             * @default 0
             */
            caffeine: number | null;
            vitamins: components["schemas"]["Vitamins"] | null;
            minerals: components["schemas"]["Minerals"] | null;
            fats: components["schemas"]["Fats"] | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** User Id */
            user_id?: string | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Minerals */
        Minerals: {
            /**
             * Calcium
             * @default 0
             */
            calcium: number | null;
            /**
             * Magnesium
             * @default 0
             */
            magnesium: number | null;
            /**
             * Phosphorus
             * @default 0
             */
            phosphorus: number | null;
            /**
             * Sodium
             * @default 0
             */
            sodium: number | null;
            /**
             * Sulfur
             * @default 0
             */
            sulfur: number | null;
            /**
             * Iron
             * @default 0
             */
            iron: number | null;
            /**
             * Zinc
             * @default 0
             */
            zinc: number | null;
            /**
             * Copper
             * @default 0
             */
            copper: number | null;
            /**
             * Manganese
             * @default 0
             */
            manganese: number | null;
            /**
             * Molybdenum
             * @default 0
             */
            molybdenum: number | null;
            /**
             * Selenium
             * @default 0
             */
            selenium: number | null;
            /**
             * Iodine
             * @default 0
             */
            iodine: number | null;
            /**
             * Fluoride
             * @default 0
             */
            fluoride: number | null;
            /**
             * Chromium
             * @default 0
             */
            chromium: number | null;
            /**
             * Potassium
             * @default 0
             */
            potassium: number | null;
            /**
             * Taurine
             * @default 0
             */
            taurine: number | null;
        };
        /** RecipeEdit */
        RecipeEdit: {
            /** Food Items */
            food_items: (components["schemas"]["ExistingRecipeItemInput"] | components["schemas"]["EntryItemInput"])[];
            /** Name */
            name: string;
        };
        /** RecipeInput */
        RecipeInput: {
            /** Name */
            name: string;
            /** Food Items */
            food_items: components["schemas"]["EntryItemInput"][];
        };
        /** RecipeItemOutput */
        RecipeItemOutput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Food Id
             * Format: uuid
             */
            food_id: string;
            /** Food Grams */
            food_grams: number;
            food: components["schemas"]["FoodOutput"];
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Food Entry Id
             * Format: uuid
             */
            food_entry_id: string;
        };
        /** RecipeOutput */
        RecipeOutput: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Name */
            name: string;
            /** Food Items */
            food_items: components["schemas"]["RecipeItemOutput"][];
            /**
             * Kcal
             * @default 0
             */
            kcal: number;
            /**
             * Protein
             * @default 0
             */
            protein: number;
            /**
             * Fat
             * @default 0
             */
            fat: number;
            /**
             * Carbs
             * @default 0
             */
            carbs: number;
            /**
             * Alcohol
             * @default 0
             */
            alcohol: number;
            /**
             * Caffeine
             * @default 0
             */
            caffeine: number;
            /**
             * Food Grams
             * @default 0
             */
            food_grams: number;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /** Token Type */
            token_type: string;
        };
        /** UserPrivate */
        UserPrivate: {
            /** Name */
            name?: string | null;
            /**
             * Id
             * Format: uuid4
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** UserPublic */
        UserPublic: {
            /** Name */
            name?: string | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Name */
            name?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Vitamins */
        Vitamins: {
            /**
             * Vit A
             * @default 0
             */
            vit_a: number | null;
            /**
             * Vit B1
             * @default 0
             */
            vit_b1: number | null;
            /**
             * Vit B2
             * @default 0
             */
            vit_b2: number | null;
            /**
             * Vit B3
             * @default 0
             */
            vit_b3: number | null;
            /**
             * Pantothenic Acid
             * @default 0
             */
            pantothenic_acid: number | null;
            /**
             * Vit B6
             * @default 0
             */
            vit_b6: number | null;
            /**
             * Vit B7
             * @default 0
             */
            vit_b7: number | null;
            /**
             * Biotin
             * @default 0
             */
            biotin: number | null;
            /**
             * Vit B9
             * @default 0
             */
            vit_b9: number | null;
            /**
             * Vit B12
             * @default 0
             */
            vit_b12: number | null;
            /**
             * Vit C
             * @default 0
             */
            vit_c: number | null;
            /**
             * Vit D
             * @default 0
             */
            vit_d: number | null;
            /**
             * Vit E
             * @default 0
             */
            vit_e: number | null;
            /**
             * Vit K
             * @default 0
             */
            vit_k: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_user_custom_food_api_foods_custom_foods_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOutput"][];
                };
            };
        };
    };
    create_custom_food_api_foods_custom_foods_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFoodInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_food_by_name_api_foods__food_name__get: {
        parameters: {
            query?: {
                page?: number;
                page_size?: number;
            };
            header?: never;
            path: {
                food_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_custom_food_api_foods_custom_foods__food_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomFoodInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_recipes_api_recipes_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOutput"][];
                };
            };
        };
    };
    create_recipe_api_recipes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_recipe_api_recipes__recipe_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecipeEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecipeOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_recipe_api_recipes__recipe_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_entry_from_recipe_api_recipes__recipe_id__food_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recipe_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_food_entries_by_date_api_food_entries__date__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOutput"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_food_entry_api_food_entries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EntryItemInput"][];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_food_entry_food_items_api_food_entries__food_entry_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_entry_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": (components["schemas"]["ExistingEntryItemInput"] | components["schemas"]["EntryItemInput"])[];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_food_entry_api_food_entries__food_entry_uuid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                food_entry_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPublic"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_api_users_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_api_users_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_current_user_api_users_me_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
        };
    };
    update_user_api_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPrivate"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_food_entry_item_api_food_entry_items__item_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FoodEntryItemEdit"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FoodEntryItemOutput"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
